export const SET_USER = 'SET_USER';
export const USERS_ERROR = 'USERS_ERROR'
export const LOAD_PROPERTIES = 'LOAD_PROPERTIES'
export const CREATE_PROPERTY = 'CREATE_PROPERTY'
export const REMOVE_PROPERTY = 'REMOVE_PROPERTY'
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY'